---
- name: Tests for OIM
  hosts: all
  remote_user: "{{ user_for_oim }}"
  tags: test

  vars_prompt:
    - name: "user_for_oim"
      prompt: "Please enter the username (without sudo)"
      private: no
      
    - name: "base"
      prompt: "Please enter the protocol, (sub)domains, and port or enter for the default"
      default: "http://localhost:8984"
      private: no

      
  tasks:
  - name: Any website
    uri:
      url: "https://www.google.com"

  - name: Landing page
    uri:
      url: "{{base}}/CSD"

  - name: Add Test Document
    uri:
      url: "{{base}}/CSD/createDirectory"
      method: POST
      body: "directory=test"
      follow_redirects: all

  - name: List Shared Value Sets
    uri:
      url: "{{base}}/CSD/SVS/initSharedValueSet"

  - name: List Stored Functions
    uri:
      url: "{{base}}/CSD/storedFunctions"

  - name: Export Stored Functions
    uri:
      url: "{{base}}/CSD/storedFunctions/export_funcs"

  - name: List Sample Dirs
    uri:
      url: "{{base}}/CSD/initSampleDirectory"

  - name: Load Provider Sample Dir
    uri:
      url: "{{base}}/CSD/initSampleDirectory/directory/providers/load"

  - name: Get Providers Sample Dir
    uri:
      url: "{{base}}/CSD/initSampleDirectory/directory/providers/get"

  - name: Reload Providers Sample Dir
    uri:
      url: "{{base}}/CSD/initSampleDirectory/directory/providers/reload"

  - name: Delete Providers Sample Dir
    uri:
      url: "{{base}}/CSD/deleteDirectory/providers"

  - name: Remove Test Document
    uri:
      url: "{{base}}/CSD/deleteDirectory/test"
