---
- name: Preparation for OIM
  hosts: all
  remote_user: "{{ user_for_oim }}"
  become: true
  tags: prep

  vars_prompt:
    - name: "user_for_oim"
      prompt: "Please enter the username (with sudo)"
      private: no

  tasks:
  - name: Ensure git
    yum:
      name: git
      state: present

  - name: Ensure wget
    yum:
      name: wget
      state: present

  - name: Ensure unzip
    yum:
      name: unzip
      state: present

  - name: Ensure java 8
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: Ensure php
    yum:
      name: php
      state: present

  - name: Ensure php-xml
    yum:
      name: php-xml
      state: present

  - name: Ensure libxml2
    yum:
      name: libxml2
      state: present

  - name: Ensure firewalld
    yum:
      name: firewalld
      state: present

  - name: open 8984
    firewalld:
      port: 8984/tcp
      permanent: true
      state: enabled

  - name: reload firewall
    command: firewall-cmd --reload
    